export const sv7 = {
  data: {
    id: "sv7",
    name: "Stellar Crown",
    series: "Scarlet & Violet",
    printedTotal: 142,
    total: 175,
    legalities: {
      unlimited: "Legal",
      standard: "Legal",
      expanded: "Legal",
    },
    ptcgoCode: "SCR",
    releaseDate: "2024/09/13",
    updatedAt: "2024/08/02 15:00:00",
    images: {
      symbol: "https://images.pokemontcg.io/sv7/symbol.png",
      logo: "https://images.pokemontcg.io/sv7/logo.png",
    },
  },
};

export const carddata = {
  data: [
    {
      id: "sv7-1",
      name: "Venusaur ex",
      supertype: "Pokémon",
      subtypes: ["Stage 2", "ex"],
      hp: "340",
      types: ["Grass"],
      evolvesFrom: "Ivysaur",
      rules: [
        "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
      ],
      abilities: [
        {
          name: "Tranquil Flower",
          text: "Once during your turn, if this Pokémon is in the Active Spot, you may heal 60 damage from 1 of your Pokémon.",
          type: "Ability",
        },
      ],
      attacks: [
        {
          name: "Dangerous Toxwhip",
          cost: ["Grass", "Grass", "Colorless"],
          convertedEnergyCost: 3,
          damage: "150",
          text: "Your opponent's Active Pokémon is now Confused and Poisoned.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless", "Colorless", "Colorless", "Colorless"],
      convertedRetreatCost: 4,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "1",
      rarity: "Double Rare",
      nationalPokedexNumbers: [3],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "G",
      images: {
        small: "https://images.pokemontcg.io/sv7/1.png",
        large: "https://images.pokemontcg.io/sv7/1_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-1",
        updatedAt: "2025/02/09",
        prices: {
          holofoil: {
            low: 0.35,
            mid: 1.28,
            high: 40,
            market: 1.77,
            directLow: 3.74,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-1",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 1.55,
          lowPrice: 0.5,
          trendPrice: 1.8,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0,
          reverseHoloLow: 0,
          reverseHoloTrend: 0,
          lowPriceExPlus: 0.5,
          avg1: 1.9,
          avg7: 1.7,
          avg30: 1.63,
          reverseHoloAvg1: 0,
          reverseHoloAvg7: 0,
          reverseHoloAvg30: 0,
        },
      },
    },
    {
      id: "sv7-2",
      name: "Ledyba",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "60",
      types: ["Grass"],
      evolvesTo: ["Ledian"],
      attacks: [
        {
          name: "Headbutt Bounce",
          cost: ["Colorless", "Colorless"],
          convertedEnergyCost: 2,
          damage: "30",
          text: "",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "2",
      rarity: "Common",
      nationalPokedexNumbers: [165],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/2.png",
        large: "https://images.pokemontcg.io/sv7/2_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-2",
        updatedAt: "2025/02/09",
        prices: {
          normal: {
            low: 0.01,
            mid: 0.08,
            high: 3.99,
            market: 0.03,
            directLow: 0.02,
          },
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.13,
            directLow: 0.12,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-2",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.03,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.1,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.11,
          lowPriceExPlus: 0.02,
          avg1: 0.03,
          avg7: 0.03,
          avg30: 0.03,
          reverseHoloAvg1: 0.1,
          reverseHoloAvg7: 0.11,
          reverseHoloAvg30: 0.1,
        },
      },
    },
    {
      id: "sv7-3",
      name: "Ledian",
      supertype: "Pokémon",
      subtypes: ["Stage 1"],
      hp: "90",
      types: ["Grass"],
      evolvesFrom: "Ledyba",
      abilities: [
        {
          name: "Glittering Star Pattern",
          text: "When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may switch in 1 of your opponent's Benched Pokémon that has 90 HP or less remaining to the Active Spot.",
          type: "Ability",
        },
      ],
      attacks: [
        {
          name: "Swift",
          cost: ["Colorless", "Colorless"],
          convertedEnergyCost: 2,
          damage: "70",
          text: "This attack's damage isn't affected by Weakness or Resistance, or by any effects on your opponent's Active Pokémon.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "3",
      rarity: "Rare",
      nationalPokedexNumbers: [166],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/3.png",
        large: "https://images.pokemontcg.io/sv7/3_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-3",
        updatedAt: "2025/02/09",
        prices: {
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.11,
            directLow: 0.11,
          },
          holofoil: {
            low: 0.01,
            mid: 0.11,
            high: 3.99,
            market: 0.09,
            directLow: 0.08,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-3",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.05,
          lowPrice: 0.02,
          trendPrice: 0.04,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.14,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.1,
          lowPriceExPlus: 0.02,
          avg1: 0.05,
          avg7: 0.04,
          avg30: 0.05,
          reverseHoloAvg1: 0.08,
          reverseHoloAvg7: 0.09,
          reverseHoloAvg30: 0.12,
        },
      },
    },
    {
      id: "sv7-5",
      name: "Lileep",
      supertype: "Pokémon",
      subtypes: ["Stage 1"],
      hp: "100",
      types: ["Grass"],
      evolvesFrom: "Antique Root Fossil",
      evolvesTo: ["Cradily"],
      attacks: [
        {
          name: "Bind Down",
          cost: ["Grass"],
          convertedEnergyCost: 1,
          damage: "50",
          text: "During your opponent's next turn, the Defending Pokémon can't retreat.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless", "Colorless"],
      convertedRetreatCost: 2,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "5",
      rarity: "Common",
      nationalPokedexNumbers: [345],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/5.png",
        large: "https://images.pokemontcg.io/sv7/5_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-5",
        updatedAt: "2025/02/09",
        prices: {
          normal: {
            low: 0.01,
            mid: 0.1,
            high: 3.99,
            market: 0.05,
            directLow: 0.03,
          },
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.12,
            directLow: 0.12,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-5",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.03,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.1,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.12,
          lowPriceExPlus: 0.02,
          avg1: 0.03,
          avg7: 0.03,
          avg30: 0.03,
          reverseHoloAvg1: 0.1,
          reverseHoloAvg7: 0.12,
          reverseHoloAvg30: 0.11,
        },
      },
    },
    {
      id: "sv7-4",
      name: "Celebi",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "80",
      types: ["Grass"],
      attacks: [
        {
          name: "Collect",
          cost: ["Colorless"],
          convertedEnergyCost: 1,
          damage: "",
          text: "Draw a card.",
        },
        {
          name: "Leaf Step",
          cost: ["Grass"],
          convertedEnergyCost: 1,
          damage: "30",
          text: "",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "4",
      rarity: "Uncommon",
      nationalPokedexNumbers: [251],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/4.png",
        large: "https://images.pokemontcg.io/sv7/4_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-4",
        updatedAt: "2025/02/09",
        prices: {
          normal: {
            low: 0.01,
            mid: 0.1,
            high: 3.99,
            market: 0.06,
            directLow: 0.03,
          },
          reverseHolofoil: {
            low: 0.01,
            mid: 0.17,
            high: 3.99,
            market: 0.17,
            directLow: 0.17,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-4",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.03,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.12,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.17,
          lowPriceExPlus: 0.02,
          avg1: 0.03,
          avg7: 0.02,
          avg30: 0.03,
          reverseHoloAvg1: 0.38,
          reverseHoloAvg7: 0.14,
          reverseHoloAvg30: 0.13,
        },
      },
    },
    {
      id: "sv7-6",
      name: "Cradily",
      supertype: "Pokémon",
      subtypes: ["Stage 2"],
      hp: "150",
      types: ["Grass"],
      evolvesFrom: "Lileep",
      abilities: [
        {
          name: "Selective Slime",
          text: "Once during your turn, you may flip a coin. If heads, choose Burned, Confused, or Poisoned. Your opponent's Active Pokémon is now affected by that Special Condition.",
          type: "Ability",
        },
      ],
      attacks: [
        {
          name: "Miasma Wind",
          cost: ["Grass"],
          convertedEnergyCost: 1,
          damage: "100×",
          text: "This attack does 100 damage for each Special Condition affecting your opponent's Active Pokémon.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless", "Colorless", "Colorless"],
      convertedRetreatCost: 3,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "6",
      rarity: "Rare",
      nationalPokedexNumbers: [346],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/6.png",
        large: "https://images.pokemontcg.io/sv7/6_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-6",
        updatedAt: "2025/02/09",
        prices: {
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.12,
            directLow: 0.12,
          },
          holofoil: {
            low: 0.01,
            mid: 0.12,
            high: 3.99,
            market: 0.09,
            directLow: 0.09,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-6",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.06,
          lowPrice: 0.02,
          trendPrice: 0.06,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.15,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.15,
          lowPriceExPlus: 0.02,
          avg1: 0.04,
          avg7: 0.06,
          avg30: 0.06,
          reverseHoloAvg1: 0.14,
          reverseHoloAvg7: 0.13,
          reverseHoloAvg30: 0.15,
        },
      },
    },
    {
      id: "sv7-7",
      name: "Carnivine",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "110",
      types: ["Grass"],
      attacks: [
        {
          name: "Nosh",
          cost: ["Colorless"],
          convertedEnergyCost: 1,
          damage: "",
          text: "Heal 40 damage from this Pokémon.",
        },
        {
          name: "Loom Over",
          cost: ["Grass", "Colorless", "Colorless"],
          convertedEnergyCost: 3,
          damage: "130-",
          text: "This attack does 10 less damage for each damage counter on this Pokémon.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless", "Colorless"],
      convertedRetreatCost: 2,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "7",
      rarity: "Common",
      nationalPokedexNumbers: [455],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/7.png",
        large: "https://images.pokemontcg.io/sv7/7_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-7",
        updatedAt: "2025/02/09",
        prices: {
          reverseHolofoil: {
            low: 0.01,
            mid: 0.13,
            high: 3.99,
            market: 0.11,
            directLow: 0.1,
          },
          normal: {
            low: 0.01,
            mid: 0.08,
            high: 3.99,
            market: 0.03,
            directLow: 0.02,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-7",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.02,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.12,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.11,
          lowPriceExPlus: 0.02,
          avg1: 0.02,
          avg7: 0.02,
          avg30: 0.02,
          reverseHoloAvg1: 0.02,
          reverseHoloAvg7: 0.12,
          reverseHoloAvg30: 0.13,
        },
      },
    },
    {
      id: "sv7-9",
      name: "Grubbin",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "70",
      types: ["Grass"],
      evolvesTo: ["Charjabug"],
      attacks: [
        {
          name: "Ambush",
          cost: ["Colorless", "Colorless"],
          convertedEnergyCost: 2,
          damage: "10+",
          text: "Flip a coin. If heads, this attack does 30 more damage.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless", "Colorless"],
      convertedRetreatCost: 2,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "9",
      rarity: "Common",
      nationalPokedexNumbers: [736],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/9.png",
        large: "https://images.pokemontcg.io/sv7/9_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-9",
        updatedAt: "2025/02/09",
        prices: {
          normal: {
            low: 0.01,
            mid: 0.09,
            high: 3.99,
            market: 0.05,
            directLow: 0.02,
          },
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.11,
            directLow: 0.14,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-9",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.02,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.13,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.11,
          lowPriceExPlus: 0.02,
          avg1: 0.02,
          avg7: 0.02,
          avg30: 0.02,
          reverseHoloAvg1: 0.07,
          reverseHoloAvg7: 0.09,
          reverseHoloAvg30: 0.12,
        },
      },
    },
    {
      id: "sv7-8",
      name: "Mow Rotom",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "90",
      types: ["Grass"],
      attacks: [
        {
          name: "Reaping Dash",
          cost: ["Colorless"],
          convertedEnergyCost: 1,
          damage: "30",
          text: "Before doing damage, discard all Pokémon Tools and Special Energy from your opponent's Active Pokémon.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "8",
      rarity: "Common",
      nationalPokedexNumbers: [479],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/8.png",
        large: "https://images.pokemontcg.io/sv7/8_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-8",
        updatedAt: "2025/02/09",
        prices: {
          reverseHolofoil: {
            low: 0.01,
            mid: 0.15,
            high: 3.99,
            market: 0.13,
            directLow: 0.15,
          },
          normal: {
            low: 0.01,
            mid: 0.1,
            high: 3.99,
            market: 0.05,
            directLow: 0.03,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-8",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.02,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.11,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.14,
          lowPriceExPlus: 0.02,
          avg1: 0.03,
          avg7: 0.03,
          avg30: 0.03,
          reverseHoloAvg1: 0.11,
          reverseHoloAvg7: 0.11,
          reverseHoloAvg30: 0.11,
        },
      },
    },
    {
      id: "sv7-10",
      name: "Gossifleur",
      supertype: "Pokémon",
      subtypes: ["Basic"],
      hp: "60",
      types: ["Grass"],
      evolvesTo: ["Eldegoss"],
      attacks: [
        {
          name: "Double Spin",
          cost: ["Colorless"],
          convertedEnergyCost: 1,
          damage: "10×",
          text: "Flip 2 coins. This attack does 10 damage for each heads.",
        },
      ],
      weaknesses: [
        {
          type: "Fire",
          value: "×2",
        },
      ],
      retreatCost: ["Colorless"],
      convertedRetreatCost: 1,
      set: {
        id: "sv7",
        name: "Stellar Crown",
        series: "Scarlet & Violet",
        printedTotal: 142,
        total: 175,
        legalities: {
          unlimited: "Legal",
          standard: "Legal",
          expanded: "Legal",
        },
        ptcgoCode: "SCR",
        releaseDate: "2024/09/13",
        updatedAt: "2024/09/13 15:00:00",
        images: {
          symbol: "https://images.pokemontcg.io/sv7/symbol.png",
          logo: "https://images.pokemontcg.io/sv7/logo.png",
        },
      },
      number: "10",
      rarity: "Common",
      nationalPokedexNumbers: [829],
      legalities: {
        unlimited: "Legal",
        standard: "Legal",
        expanded: "Legal",
      },
      regulationMark: "H",
      images: {
        small: "https://images.pokemontcg.io/sv7/10.png",
        large: "https://images.pokemontcg.io/sv7/10_hires.png",
      },
      tcgplayer: {
        url: "https://prices.pokemontcg.io/tcgplayer/sv7-10",
        updatedAt: "2025/02/09",
        prices: {
          normal: {
            low: 0.01,
            mid: 0.08,
            high: 3.99,
            market: 0.03,
            directLow: 0.02,
          },
          reverseHolofoil: {
            low: 0.01,
            mid: 0.13,
            high: 3.99,
            market: 0.11,
            directLow: 0.11,
          },
        },
      },
      cardmarket: {
        url: "https://prices.pokemontcg.io/cardmarket/sv7-10",
        updatedAt: "2025/02/09",
        prices: {
          averageSellPrice: 0.03,
          lowPrice: 0.02,
          trendPrice: 0.04,
          germanProLow: 0,
          suggestedPrice: 0,
          reverseHoloSell: 0.09,
          reverseHoloLow: 0.02,
          reverseHoloTrend: 0.08,
          lowPriceExPlus: 0.02,
          avg1: 0.03,
          avg7: 0.03,
          avg30: 0.03,
          reverseHoloAvg1: 0.06,
          reverseHoloAvg7: 0.08,
          reverseHoloAvg30: 0.09,
        },
      },
    },
  ],
};
